# Generated by Django 3.2.3 on 2023-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_businformation_bus_viaroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
