# Generated by Django 3.2.3 on 2023-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='stop_id',
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
