# Generated by Django 3.2.3 on 2023-06-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20230601_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businformation',
            old_name='bus_sourcetodestination',
            new_name='bus_source',
        ),
        migrations.AddField(
            model_name='businformation',
            name='bus_destination',
            field=models.CharField(default='hello', max_length=80),
            preserve_default=False,
        ),
    ]
